### PR TITLE
Add instructions to enable paid workers plan

### PR DESCRIPTION
**Pull request by jonikanerva**
Workers plan is required to enable queues

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
As a note, this kinda makes a huge difference in the appeal of running Wildebeest without a *bit* more info. Images being set-tier pricing means I don't have to worry about suddenly surprise bills when Elon Musk drives a ton more traffic to the fediverse at random. Adding a requirement of a pay-as-you-go offering is a *huge* impact.

I'm interested in potentially using Wildebeest, but I do not have spare funds for experiments, so I probably need at least a good faith expectation of how much running it will cost me. Perhaps some of the CF employees running it  in production can provide enough numbers to estimate the consumer cost?

**Comment by otherjoel** [comment]
@jonikanerva did you intend to close this?

**Comment by jonikanerva** [comment]
> @jonikanerva did you intend to close this?

Ah no! I forgot I still had this PR open and deleted my fork. 🤦

**Comment by KianNH** [comment]
> Images being set-tier pricing means I don't have to worry about suddenly surprise bills when Elon Musk drives a ton more traffic to the fediverse at random. Adding a requirement of a pay-as-you-go offering is a _huge_ impact.

FYI, Images is PAYGO pricing after your included usage - there is no cap, it'll be the same model as a Workers paid plan.

**Comment by AndyNortrup** [comment]
> > Images being set-tier pricing means I don't have to worry about suddenly surprise bills when Elon Musk drives a ton more traffic to the fediverse at random. Adding a requirement of a pay-as-you-go offering is a _huge_ impact.
> 
> FYI, Images is PAYGO pricing after your included usage - there is no cap, it'll be the same model as a Workers paid plan.

I don't think anyone said this would be free as in beer.  You are consuming resources that must be paid for by someone. Overtime it will be interesting to see what actual costs are for a single user instance.

**Comment by KianNH** [comment]
> > > Images being set-tier pricing means I don't have to worry about suddenly surprise bills when Elon Musk drives a ton more traffic to the fediverse at random. Adding a requirement of a pay-as-you-go offering is a _huge_ impact.
> > 
> > 
> > FYI, Images is PAYGO pricing after your included usage - there is no cap, it'll be the same model as a Workers paid plan.
> 
> I don't think anyone said this would be free as in beer. You are consuming resources that must be paid for by someone. Overtime it will be interesting to see what actual costs are for a single user instance.

Sure - I was just saying that 'Images being set-tier pricing means I don't have to worry about suddenly surprise bills' is incorrect.

**Comment by ocdtrekkie** [comment]
@AndyNortrup Definitely not concerned about paying for hosting, am just concerned about cost control/predictability.

**Review by 53jk1 — APPROVED** [review]

**Comment by xtuc** [comment]
Since the README has been rewritten is that change still needed?

**Comment by celso** [comment]
See https://github.com/cloudflare/wildebeest/blob/main/docs/requirements.md

**Pull request closed without merging**
